config/routes.rb
Rails.application.routes.draw do

  get 'labels/show'

  get 'login' => 'users#login'
  post 'authenticate' => 'users#authenticate'
  get 'logout' => 'users#logout'

  resources :documents, only: [:index, :create, :destroy] do
    member do
      get 'open'
      patch 'attach_label'
      patch 'detach_label'
    end
    collection do
      get 'search'
    end
  end

  resources :labels, only: [:show, :create, :destroy]

  post 'modules/:module_name' => 'modules#render_module'

  root 'documents#index'

end

app/models/document.rb
class Document < ActiveRecord::Base

  # Associations
  belongs_to :owner, class_name: "User", foreign_key: "user_id"
  has_and_belongs_to_many :labels, -> { uniq }

  # Attached files
  mount_uploader :file, DocumentUploader

  # Callbacks
  before_validation :convert_image_to_pdf, on: :create

  # Validations
  validates :owner, presence: true
  validates :title, presence: true
  validates :file, presence: true
  validates :labels, same_user_ids: true

  # Scopes
  default_scope { includes(:labels).order(created_at: :desc) }

  # Class methods

  def self.from_file(params)
    if params[:file]
      filename = params[:file].respond_to?(:original_filename) ? params[:file].original_filename : File.basename(params[:file])
      title = File.basename(filename, File.extname(filename))
      Document.new(params.merge(title: title))
    else
      Document.new(params)
    end
  end

  def self.search(query)
    if query.present?
      rank = "ts_rank(to_tsvector('simple', title), plainto_tsquery(#{sanitize(query)}))"
      search_query = "to_tsvector('simple', title) @@ :q OR "
      search_query += "to_tsvector('simple', title) @@ plainto_tsquery(:q)"
      where(search_query, q: query).order("#{rank} desc")
    else
      all
    end
  end

  # Instance methods

  private

  def convert_image_to_pdf
    uploaded_file = file.file
    if uploaded_file.present? && !uploaded_file.content_type.nil? && uploaded_file.content_type.start_with?("image/")
      image_path = file.current_path
      pdf_path = File.dirname(file.current_path) + "/" + File.basename(uploaded_file.file.sub(/\.[^\.]*$/, ".pdf"))
      if Paperless::PDFUtils.convert_image_to_pdf image_path, pdf_path
        self.file = File.new pdf_path
        true
      else
        errors[:file] = "cannot be converted imto a PDF file"
        false
      end
    end
  end
end

app/models/label.rb
class Label < ActiveRecord::Base

  # Associations
  belongs_to :user
  has_and_belongs_to_many :documents, -> { uniq }

  # Validations
  validates :name, presence: true
  validates :name, uniqueness: {scope: :user_id}
  validates :documents, same_user_ids: true

  # Scopes
  default_scope { order(name: :asc) }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  # Associations
  has_many :documents, dependent: :destroy
  has_many :labels, dependent: :destroy

  # Validations
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :password, presence: {on: :create}

  # Instance methods

  def full_name
    "#{first_name} #{last_name}"
  end

  def avatar_url
    gravatar_id = Digest::MD5.hexdigest(email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=48"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  before_filter :authenticated!, except: [:login, :logout, :authenticate]
  before_filter :load_user_objects, except: [:login, :logout, :authenticate]

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def load_user_objects
    load_user_labels
    create_new_document
    create_new_label
  end

  def create_new_document
    @new_document = current_user.documents.new
  end

  def create_new_label
    @new_label = current_user.labels.new
  end

  def load_user_labels
    @user_labels = current_user.labels
  end

  def authenticated!
    redirect_to login_path unless current_user
    return
  end

  def paginate_documents(documents)
    @page = params[:page]
    documents.paginate page: @page, per_page: 15
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  def index
    @documents = paginate_documents current_user.documents
  end

  def create
    document = current_user.documents.from_file(document_params)
    document.save
    respond_to do |format|
      format.js {render nothing: true}
    end
  end

  def open
    document = current_user.documents.find(params[:id])
    send_file document.file.url, disposition: :inline
  end

  def destroy
    document = current_user.documents.find(params[:id])
    document.destroy
    redirect_to :back
  end

  def search
    @query = params[:query]
    @documents = paginate_documents current_user.documents.search(@query)
  end

  def attach_label
    document = current_user.documents.find(params[:id])
    label = current_user.labels.find(params[:label_id])
    document.labels << label
    document.save
    respond_to do |format|
      format.js {render nothing: true}
    end
  end

  def detach_label
    document = current_user.documents.find(params[:id])
    label = current_user.labels.find(params[:label_id])
    document.labels.delete label
    document.save
    respond_to do |format|
      format.js {render nothing: true}
    end
  end

  private

  def document_params
    params.require(:document).permit(:file, label_ids: [])
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController

  def show
    @label = current_user.labels.find(params[:id])
    @documents = paginate_documents @label.documents
  end

  def create
    label = current_user.labels.new(label_params)
    label.save
    redirect_to :back
  end

  def destroy
    label = current_user.labels.find(params[:id])
    label.destroy
    redirect_to :back
  end

  private

  def label_params
    params.require(:label).permit(:name)
  end
end

app/controllers/modules_controller.rb
class ModulesController < ApplicationController
  layout :false

  ALLOWED_MODULES = [:progress_bar]

  # Allow to retrieve a module HTML code from an ajax call
  def render_module
    @module_name = params[:module_name]
    if !is_module_allowed? @module_name
      return render nothing: true, status: 404
    end
    @locals = params[:locals]
  end

  private

  # Test if a module is allowed to be delivered using AJAX
  def is_module_allowed?(module_name)
    ALLOWED_MODULES.include? module_name.to_sym
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login
    render layout: "login"
  end

  def authenticate
    @email = params[:email]
    user = User.find_by(email: @email).try(:authenticate, params[:password])
    if user
      session[:user_id] = user.id
      redirect_to documents_path
    else
      render :login, layout: "login"
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def render_module(module_name, locals = {})
    render partial: "modules/#{module_name}", locals: locals
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/documents/index.html.haml
= render_module "document_list", list_name: "All documents", documents: @documents

app/views/documents/search.html.haml
= render_module "document_list", list_name: "Search results: #{@query}", documents: @documents

app/views/labels/show.html.haml
= render_module "document_list", list_name: @label.name, documents: @documents

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Paperless
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .overlay

    %header#header
      #logo
        %h1 Paperless
      #search-form
        = render_module :document_search_form, query: @query
      #user
        = render_module :user_card, user: current_user

    #content-wrapper
      %nav#content-nav
        %ul.navigation-list
          %li= link_to "All documents", documents_path
          %li= render_module :document_upload, document: @new_document
          %hr
          - @user_labels.each do |label|
            - if !label.new_record?
              %li
                = render_module :label, label: label, state: "is-label-draggable"
                %ul.action-list
                  %li= link_to "Delete", label_path(label.id), method: :delete, data: {confirm: "Are you sure ?"}
          %li= render_module :label_creation, label: @new_label
      #content-main
        = yield

app/views/layouts/login.html.haml
!!! 5
%html
  %head
    %title Paperless
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    #login-form
      = yield

app/views/modules/_document_list.html.haml
.document-list
  %h3= list_name
  %h4= "#{documents.total_entries} documents found"
  %ul
    - documents.each do |document|
      %li.document-list-entry.is-label-droppable{data: {on_label_drop: "updateDocumentLabels", attach_label_document_path: attach_label_document_path(document.id), detach_label_document_path: detach_label_document_path(document.id)}}
        %h5.document-list-entry-title= link_to document.title, open_document_path(document.id)
        %ul.action-list
          %li= link_to "Delete", document_path(document.id), method: :delete,
          data: {confirm: "Are you sure ?"}
        %ul.label-list
          - document.labels.each do |label|
            %li= render_module :label, label: label, state: "is-label-pinned"
  .document-list-pagination= will_paginate documents

app/views/modules/_document_search_form.html.haml
.document-search-form
  = form_tag search_documents_path, method: :get, class: "one-line-form" do
    = text_field_tag :query, query
    = submit_tag "Search", class: "button"

app/views/modules/_document_upload.html.haml
.document-upload
  = link_to "Upload documents", "#upload-document", class: "button document-upload-link"
  .document-upload-progress
    %h2 Documents are being sent to the server
    .document-upload-progress-queue
    = link_to "Return to the documents page", documents_path, class: "document-upload-progress-return-button button is-button-disabled"
  = form_for document, html: {class: "document-upload-form"} do |f|
    = f.file_field :file, multiple: true, name: "document[file]"

app/views/modules/_label.html.haml
.label{data: {label_id: label.id}, class: defined?(state) ? state : ""}
  = link_to label.name, label_path(label.id)
  %span.label-delete-link= link_to "✕", "#detach-label"
  %span.label-processing ...

app/views/modules/_label_creation.html.haml
.label-creation
  = form_for label, html: {class: "one-line-form label-creation-form"} do |f|
    = f.text_field :name
    = f.submit "Add", class: "button"
    %ul.action-list.is-always-visible
      %li= link_to "Cancel", "#cancel-label-creation", class: "label-creation-cancel-link"
  = link_to "Add label", "#add-label", class: "button label-creation-link"

app/views/modules/_login_form.html.haml
= form_tag url, class: "login-form" do
  %fieldset
    %legend Login
    = label_tag :email
    = text_field_tag :email, email
    = label_tag :password
    = password_field_tag :password
    = submit_tag "Login", class: "button"

app/views/modules/_progress_bar.html.haml
.progress-bar{id: id}
  .progress-bar-filename= filename
  .progress-bar-container
    .progress-bar-container-percent

app/views/modules/_user_card.html.haml
.user-card
  .user-card-menu
    %h2= user.full_name
    %ul.action-list.is-always-visible
      %li= link_to "Logout", logout_path
  .avatar= image_tag user.avatar_url

app/views/modules/render_module.html.haml
= render_module @module_name, @locals

app/views/users/login.html.haml
= render_module :login_form, url: authenticate_path, email: @email

app/views/users/logout.html.haml
%h1 Users#logout
%p Find me in app/views/users/logout.html.haml